version: '3.8'

services:
  attendance-frontend:
    container_name: attendance-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge
